language: node_js
node_js:
  - '7'
install:
  - npm install
  - npm install rxjs
script:
  - npm run-script build-all
  - npm run-script lint
  - npm run-script website
  - npm run-script test
after_success: npm run-script coverage
